name: QUICKLOGGER Pipeline
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install jq
        run: sudo apt-get install jq

      - name: Read version file and set environment variables
        run: |
          versions=$(cat versions.json)
          echo "$versions" | jq -r 'to_entries | .[] | "MICROSERVICE_\(.key | ascii_upcase)=\(.value)"' >> $GITHUB_ENV  

      - name: Build and Push Docker Image QUICKLOGGER API
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cod4it/quicklogger:${{ env.MICROSERVICE_QUICKLOGGER_API }}
          file: QuickLogger/Dockerfile
      
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.QUICKLOGGER_HOST }}
          username: ${{ secrets.QUICKLOGGER_USERNAME }}
          password: ${{ secrets.QUICKLOGGER_PASSWORD }}
          script:  |
            cd code
            cd QuickLogger/
            git pull
            versions=$(cat versions.json)
            readarray -t versions <<< "$(echo "$versions" | jq -r 'to_entries | .[] | "MICROSERVICE_\(.key | ascii_upcase)=\(.value)"')"; for v in "${versions[@]}"; do export "$v"; done
            envsubst < k8s.yml > k8s_ready.yml
            microk8s kubectl apply -f k8s_ready.yml